(() => {
  const CATEGORIES = ['Apps', 'Dreamors', 'Dreams', 'Circles'];
  const SORTS = ['Relevance', 'Newest', 'Oldest', 'Most active'];
  const facets = { language: ['Any language', 'English', 'Spanish', 'French'], location: ['Any location', 'Global', 'North America', 'Europe'], own: ['Show all', 'Show own'] };
  const state = { query: '', category: 'Apps', sort: 'Relevance', language: 'Any language', location: 'Any location', own: 'Show all' };
  const data = window.discoverItems || [];
  const root = document.querySelector('#discover-refine') || document.body;
  const el = (tag, attrs = {}, text = '') => { const node = document.createElement(tag); Object.entries(attrs).forEach(([key, value]) => key === 'class' ? node.className = value : node.setAttribute(key, value)); if (text) node.textContent = text; return node; };
  const saved = () => { try { return JSON.parse(localStorage.getItem('savedSearches') || '[]'); } catch { return []; } };
  const persist = list => localStorage.setItem('savedSearches', JSON.stringify(list));
  const search = el('input', { type: 'search', id: 'discover-search', placeholder: 'Search Discover', 'aria-label': 'Search Discover' });
  const toggle = el('button', { type: 'button', 'aria-expanded': 'false', 'aria-controls': 'refine-panel' }, 'Refine');
  const bar = el('div', { class: 'discover-search-bar' }); bar.append(search, toggle);
  const panel = el('section', { id: 'refine-panel', hidden: '' });
  const tabs = el('div', { role: 'tablist', 'aria-label': 'Refine options' });
  const tabPanels = new Map();
  const setTab = name => { tabs.querySelectorAll('[role=tab]').forEach(t => { const active = t.dataset.tab === name; t.setAttribute('aria-selected', String(active)); t.tabIndex = active ? 0 : -1; }); tabPanels.forEach((p, key) => { p.hidden = key !== name; }); };
  ['Categories', 'Sorting', 'Advanced'].forEach((name, i) => { const key = name.toLowerCase(); const tab = el('button', { type: 'button', role: 'tab', id: `tab-${key}`, 'aria-controls': `panel-${key}`, 'aria-selected': String(i === 0), tabindex: i === 0 ? '0' : '-1', 'data-tab': key }, name); tab.onclick = () => setTab(key); tab.onkeydown = e => { if (e.key === 'ArrowRight' || e.key === 'ArrowLeft') { e.preventDefault(); const next = e.key === 'ArrowRight' ? (i + 1) % 3 : (i + 2) % 3; tabs.children[next].focus(); setTab(['categories','sorting','advanced'][next]); } }; tabs.append(tab); });
  const choices = (label, values, prop) => { const wrap = el('fieldset'); wrap.append(el('legend', {}, label)); values.forEach(value => { const id = `${prop}-${value.toLowerCase().replace(/\\W+/g, '-')}`; const input = el('input', { type: 'radio', name: prop, id, value }); input.checked = state[prop] === value; input.onchange = () => { state[prop] = value; render(); }; const labelNode = el('label', { for: id }, value); wrap.append(input, labelNode); }); return wrap; };
  const catPanel = el('div', { id: 'panel-categories', role: 'tabpanel', 'aria-labelledby': 'tab-categories' }); catPanel.append(choices('Categories', CATEGORIES, 'category')); tabPanels.set('categories', catPanel);
  const sortPanel = el('div', { id: 'panel-sorting', role: 'tabpanel', 'aria-labelledby': 'tab-sorting', hidden: '' }); sortPanel.append(choices('Sort by', SORTS, 'sort')); tabPanels.set('sorting', sortPanel);
  const advPanel = el('div', { id: 'panel-advanced', role: 'tabpanel', 'aria-labelledby': 'tab-advanced', hidden: '' }); Object.entries(facets).forEach(([key, values]) => advPanel.append(choices(key[0].toUpperCase() + key.slice(1), values, key))); tabPanels.set('advanced', advPanel);
  panel.append(tabs, catPanel, sortPanel, advPanel);
  const actions = el('div', { class: 'refine-actions' }); const save = el('button', { type: 'button' }, 'Save search'); actions.append(save); panel.append(actions);
  const savedWrap = el('section', { 'aria-labelledby': 'saved-heading' }); savedWrap.append(el('h2', { id: 'saved-heading' }, 'Saved searches')); const savedList = el('ul'); savedWrap.append(savedList);
  const results = el('div', { id: 'discover-results', 'aria-live': 'polite' });
  const renderSaved = () => { savedList.replaceChildren(); saved().forEach((item, index) => { const li = el('li'); const load = el('button', { type: 'button' }, item.name); load.onclick = () => { Object.assign(state, item.criteria); search.value = state.query; render(); }; const del = el('button', { type: 'button', 'aria-label': `Delete ${item.name}` }, 'Delete'); del.onclick = () => { const list = saved(); list.splice(index, 1); persist(list); renderSaved(); }; li.append(load, del); savedList.append(li); }); };
  const render = () => { const q = state.query.toLowerCase(); const filtered = data.filter(item => (!q || JSON.stringify(item).toLowerCase().includes(q)) && (!state.category || item.category === state.category) && (state.language === 'Any language' || item.language === state.language) && (state.location === 'Any location' || item.location === state.location) && (state.own === 'Show all' || item.own)); results.replaceChildren(...filtered.map(item => el('article', { class: 'discover-card' }, item.name || 'Discover item'))); };
  search.oninput = () => { state.query = search.value; render(); }; toggle.onclick = () => { const open = panel.hidden; panel.hidden = !open; toggle.setAttribute('aria-expanded', String(open)); if (open) tabs.querySelector('[aria-selected=true]').focus(); }; save.onclick = () => { const name = window.prompt('Name this search', state.query || 'Untitled search'); if (!name) return; const list = saved(); list.unshift({ name, criteria: { ...state } }); persist(list); renderSaved(); }; root.replaceChildren(bar, panel, savedWrap, results); renderSaved(); render();
})();